### ISSUE TITLE
Allow using .idk (not .idk/ )

### ISSUE THREAD

**Issue by masnn** [aaronjanse/dns-over-wikipedia#5]

**Comment by BtM909** [comment]
It might have to do with the fact that .idk (where is the tld name coming from, hehe) isn't a official registered domain. So without the last slash it will actually invoke a search engine search. Adding slash explicitly tries to route you to the website.

**Comment by masnn** [comment]
but it's really annoying. is there any way to hook this event?

**Comment by aaronjanse** [comment]
One possible solution would be creating an [omnibox keyword](https://developer.chrome.com/extensions/omnibox) where the user types `idk` followed by a space or tab, then the query. To see this behavior on default Google Chrome, try typing `bing.com hacker news`.

Thoughts?

**Comment by masnn** [comment]
That seems better :D

**Comment by aaronjanse** [comment]
Fixed by https://github.com/aaronjanse/dns-over-wikipedia/commit/2b84e7b3041d5f246d7c19ee50a395dd230f9d42

**Comment by masnn** [comment]
What about simply check if url matchs https://google.com/search?q=foo.idk (etc)?

**Comment by johnsmith2077** [comment]
Firefox users could add `browser.fixup.domainsuffixwhitelist.idk` set it to `true` in `about:config`.
